name: Build & Deploy

on:
  workflow_call:

jobs:
  build:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker image metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
            images: ghcr.io/teamsbc/container-for-osbuild
            tags: |
                type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}
                type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64  # ,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          cache-from: type=registry,ref=ghcr.io/teamsbc/container-for-osbuild:latest
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
